name: Meu primeiro Workflow

on:
  push:
    branches: [ main, developer ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Teste automatizando
    runs-on: ubuntu-hosted
    steps:
      - name: Step 1
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: 'dalianeleme'
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_PASSWORD }}             
