name: Meu primeiro Workflow

on:
  push:
    branches: [ main, developer ]

jobs:
  Test:
    name: Teste automatizando
    runs-on: ubuntu-hosted
    steps:
      - name: Step 1
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: 'dalianeleme'
          password: ${{ secrets.DOCKERHUB_PASSWORD }}             
